### ISSUE TITLE
Rename commit.exs to .committee.exs

### ISSUE THREAD

**Issue by thiamsantos** [edisonywh/committee#18]
That's is a common pattern in elixir for config file, as we have for the formatter config been `.formatter.exs` and credo config file been `.credo.exs`. We could do the same thing on `committee`. I think it also would avoid confusing because `commit.exs` seems to be something really specific for pre/pos-commit hooks, and if we intend to add another types of hooks that name could be a little strange.

**Comment by edisonywh** [comment]
Ah I like this idea, I took the "inspiration" from `mix.exs`, in hindsight it's not as idiomatic :p

If you want to go ahead and make a PR, go ahead! I'd appreciate it! :)
