### ISSUE TITLE
Add tests (yeah it doesn't have any test)

### ISSUE THREAD

**Issue by edisonywh** [edisonywh/committee#2]
Well yes it's a shame, but I'm going to get to it...

Would definitely appreciate any ideas about testing though!

**Comment by thiamsantos** [comment]
As the test would rely heavily on the file system, we could create some tmp folders and simulate the complete behaviour there, WDYT?

Something similar to what the tests for elixir do:
https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/test/test_helper.exs#L17
https://github.com/elixir-lang/elixir/blob/78551c11c9c97bb608e4097d2e0c36458b11f535/lib/mix/test/mix/cli_test.exs#L21

**Comment by edisonywh** [comment]
Ah interesting, I did not know Elixir did that. I previously tested a project with a temp file solution too, I think it was using the [Briefly package](https://github.com/CargoSense/briefly), so I think you're right, temp files are the way to go. Probably needs some refactoring, I can try to get to it this week.

I think the file part is solvable, but I have less of an idea how to test something like `Helpers.staged_files/1`), because that uses git, so maybe I would need a Mock to handle that?

**Comment by thiamsantos** [comment]
> I think the file part is solvable, but I have less of an idea how to test something like Helpers.staged_files/1), because that uses git, so maybe I would need a Mock to handle that?

Instead of mocking, we could just use git. Init a new repository, create a file, stage it, and check if the function `Helpers.staged_files/1` is returning correctly.

>  Probably needs some refactoring, I can try to get to it this week.

I was starting to work on it right now, but please go ahead :)

**Comment by edisonywh** [comment]
Ah I wasn't sure if it was a good idea to use Git during test, but thinking about it doesn't seem like a huge negative.

Hey if you want to work on it, be my guest! I'm happy to review and just learn from you too, it's great to see people contributing so thanks again @thiamsantos :)

**Comment by thiamsantos** [comment]
> Hey if you want to work on it, be my guest! I'm happy to review and just learn from you too, it's great to see people contributing so thanks again @thiamsantos :)

Really nice, I'll try to send a PR this week for you to review. WDYT?
