### ISSUE TITLE
How to stop anyone committing on master branch ?

### ISSUE THREAD

**Issue by collegeimprovements** [edisonywh/committee#30]
It's possible to stop anyone comitting on master branch via git-hook.
How to do the same with committee ?

Git Hook: https://stackoverflow.com/a/40465455/835149

**Comment by edisonywh** [comment]
Yeah for sure, you'd probably just need to check if the current branch name is `master`, if so just halt. 

Have not tried it but something like this should work.

```
defmodule YourApp.Commit do
  use Committee
  import Committee.Helpers, only: [branch_name: 0]

  def pre_commit do
    case branch_name() do
      "master" -> {:halt, "Cannot commit directly on master."}
      _ -> {:ok, "Proceed."}
    end
  end
end
```

Edit: You can also do more interesting stuffs like making sure your branch names are prefixed with JIRA keys for example

Edit 2: Yup just tested it, definitely works

**Comment by collegeimprovements** [comment]
Hi @edisonywh ,

For some strage reason, it doesn't fully work. 
```elixir
defmodule UltraApi.Commit do
  @moduledoc false
  use Committee
  import Committee.Helpers, only: [staged_files: 0, staged_files: 1, branch_name: 0]

  # Here's where you can add your Git hooks!
  #
  # To abort a commit, return in the form of `{:halt, reason}`.
  # To print a success message, return in the form of `{:ok, message}`.
  #
  # ## Example:
  #
  @impl true
  @doc """
  This function auto-runs `mix format` on staged files.
  """
  def pre_commit do
    IO.inspect(branch_name(), label: "BRANCH NAME:")

    case branch_name() do
      "master" -> {:halt, "Cannot commit directly on master."}
      _ -> {:ok, "Proceed."}
    end

    System.cmd("mix", ["format"] ++ staged_files([".ex", ".exs"]))
    System.cmd("git", ["add"] ++ staged_files())
    {:ok, "mix format ran successfully on staged_files"}
  end

  #
  # If you want to test your example manually, you can run:
  #
  #   `mix committee.runner [pre_commit | post_commit]`
  #
end
```
☝🏼 is the full content of my `.committee.exs` file.

![Screenshot 2020-06-15 at 6 38 37 PM](https://user-images.githubusercontent.com/1519705/84661083-6f160e80-af37-11ea-800c-7463cebae017.png)

**Comment by edisonywh** [comment]
@collegeimprovements As with all Elixir code,`{:halt, x}` needs to be the return value of the function for it to work, in your example you return `{:halt, x}` in your case statement and then it's never used again.

In your case, you want to proceed when and only when the branch name is correct, so one way you can refactor it is to something like:

```
case branch_name() do
  "master" -> {:halt, "asd"}
  _ ->
    System.cmd("mix")...
    ...
    {:ok, "mix format ran"}
end
```

You can also refactor it to use `with` if you like

**Comment by collegeimprovements** [comment]
Thanks a lot @edisonywh . It works like a charm.
